import type { Metadata } from "next";
import "./globals.css";
import { inter_font, jetBrains_font, karla_font } from "@/assets/fonts";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla_font.variable} ${jetBrains_font.variable} ${inter_font.variable} antialiased bg-primary_color w-full max-w-[1000px] mx-auto hidden  flex-col transition-all `}
      >
        <Navbar />
        <main className="w-full gap-7 flex flex-col items-center   text-secondary_color flex-grow relative md:mt-6 mt-11 shrink-0">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
