import type { Metadata } from "next";
import "./globals.css";
import { inter_font, jetBrains_font, karla_font } from "@/assets/fonts";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${karla_font.variable} ${jetBrains_font.variable} ${inter_font.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
