import type { Metadata } from "next";
import "./globals.css";
import { inter_font, jetBrains_font, karla_font } from "@/assets/fonts";
import Navbar from "@/components/navbar";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="">
			<body
				className={`${karla_font.variable} ${jetBrains_font.variable} ${inter_font.variable} antialiased bg-primary_color w-full max-w-[1000px] mx-auto flex flex-col gap-2`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
